#
# this UI was generated by chatgpt
#

import customtkinter as ctk
import requests
import base64
from tkinter import filedialog
from PIL import Image, ImageTk

API_BASE = "https://rglmi1s1v8.execute-api.us-east-2.amazonaws.com/test"

ctk.set_appearance_mode("light")


class App(ctk.CTk):

    def __init__(self):
        super().__init__()

        self.title("Image Color Analyzer")
        self.geometry("720x700")

        # TITLE
        title = ctk.CTkLabel(self, text="Image Color Analyzer", font=("Arial", 26))
        title.pack(pady=20)

        # -------------------------
        # IMAGE UPLOAD
        # -------------------------

        upload_frame = ctk.CTkFrame(self)
        upload_frame.pack(pady=10)

        self.upload_button = ctk.CTkButton(
            upload_frame,
            text="Upload Image",
            command=self.upload_image
        )
        self.upload_button.pack(side="left", padx=10)

        self.upload_status = ctk.CTkLabel(upload_frame, text="")
        self.upload_status.pack(side="left")

        # image preview
        self.image_label = ctk.CTkLabel(self, text="")
        self.image_label.pack(pady=10)

        # -------------------------
        # GET IMAGE DETAILS
        # -------------------------

        details_frame = ctk.CTkFrame(self)
        details_frame.pack(pady=10)

        self.uuid_entry = ctk.CTkEntry(
            details_frame,
            width=350,
            placeholder_text="Enter image UUID"
        )
        self.uuid_entry.pack(side="left", padx=10)

        self.details_button = ctk.CTkButton(
            details_frame,
            text="Get Details",
            command=self.get_details
        )
        self.details_button.pack(side="left")

        # palette display
        self.palette_frame = ctk.CTkFrame(self)
        self.palette_frame.pack(pady=15)

        # scores
        self.score_label = ctk.CTkLabel(self, text="")
        self.score_label.pack()

        # -------------------------
        # SEARCH SECTION
        # -------------------------

        search_frame = ctk.CTkFrame(self)
        search_frame.pack(pady=20)

        self.score_type = ctk.CTkOptionMenu(
            search_frame,
            values=["harmony", "contrast"]
        )
        self.score_type.pack(side="left", padx=10)

        self.threshold_entry = ctk.CTkEntry(
            search_frame,
            placeholder_text="Threshold"
        )
        self.threshold_entry.pack(side="left", padx=10)

        self.search_button = ctk.CTkButton(
            search_frame,
            text="Search",
            command=self.search_images
        )
        self.search_button.pack(side="left")

        # results
        self.results_box = ctk.CTkTextbox(self, width=600, height=220)
        self.results_box.pack(pady=10)

    # -------------------------
    # UPLOAD IMAGE
    # -------------------------
    def upload_image(self):
        file_path = filedialog.askopenfilename()

        if not file_path:
            return

        try:

            # preview image
            img = Image.open(file_path)
            img.thumbnail((300, 300))

            ctk_img = ctk.CTkImage(light_image=img, size=(300,300))
            self.image_label.configure(image=ctk_img)
            self.image_label.image = ctk_img

            url = f"{API_BASE}/images"

            with open(file_path, "rb") as f:
                response = requests.post(
                    url,
                    data=f.read(),
                    headers={"Content-Type": "image/jpeg"}
                )

            print("STATUS:", response.status_code)
            print("RESPONSE:", response.text)

            data = response.json()

            self.upload_status.configure(
                text=f"Uploaded! Image ID: {data['image_id']}"
            )

        except Exception as e:
            self.upload_status.configure(text=f"Upload error: {e}")

    
    # -------------------------
    # GET IMAGE DETAILS
    # -------------------------

    def get_details(self):

        image_id = self.uuid_entry.get()

        if not image_id:
            return

        try:

            url = f"{API_BASE}/images/{image_id}"
            response = requests.get(url)

            data = response.json()

            # clear palette
            for widget in self.palette_frame.winfo_children():
                widget.destroy()

            # display palette
            if "palette" in data:
                for color in data["palette"]:
                    square = ctk.CTkFrame(
                        self.palette_frame,
                        width=40,
                        height=40,
                        fg_color=color
                    )
                    square.pack(side="left", padx=5)

            harmony = data.get("harmony_score", "N/A")
            contrast = data.get("contrast_score", "N/A")

            self.score_label.configure(
                text=f"Harmony Score: {harmony}   |   Contrast Score: {contrast}"
            )

        except Exception as e:
            self.score_label.configure(text=f"Error retrieving image: {e}")

    # -------------------------
    # SEARCH IMAGES
    # -------------------------

    def search_images(self):

        score_type = self.score_type.get()
        threshold = self.threshold_entry.get()

        try:

            url = f"{API_BASE}/images/search"

            params = {
                "score_type": score_type,
                "threshold": threshold
            }

            response = requests.get(url, params=params)

            data = response.json()

            self.results_box.delete("1.0", "end")

            for item in data:
                score = list(item.values())[1]

                self.results_box.insert(
                    "end",
                    f"{item['image_id']} | {score_type}: {score}\n"
                )

        except Exception as e:
            self.results_box.insert("end", f"Search error: {e}")


app = App()
app.mainloop()